# Generated by Django 3.1.7 on 2021-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210503_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
