# Generated by Django 3.1.7 on 2021-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210503_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
