# Generated by Django 3.1.7 on 2021-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210507_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/no-img.png', null=True, upload_to=''),
        ),
    ]
